disable permission which is complained by terraform
error: Invalid for_each argument

  on .terraform/modules/my_studies_sql_import_bucket/terraform-google-cloud-storage-1.5.0/modules/simple_bucket/main.tf line 64, in resource "google_storage_bucket_iam_member" "members":
  64:   for_each = {
  65:     for m in var.iam_members : "${m.role} ${m.member}" => m
  66:   }

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

[terragrunt] 2020/05/05 22:03:13 Hit multiple errors: