Specify version for google-api-core so that it's compatible with pubsub.
I was seeing this error:

ERROR: google-cloud-pubsub 1.4.3 has requirement
google-api-core[grpc]<1.17.0,>=1.14.0, but you'll have google-api-core
1.17.0 which is incompatible.

Change-Id: Ib66bb1a0fa41ece58ab4229cfe6cd823112436c3